Web site
pandademonium/Object-Detection-Telegram-Bot pull request #15
Opened 2020-10-23 17:31 UTC by pavelbystrov1

Сделал аналог чат бота на флаге,  только у нас пока не было лекций про динамическое отображение картинок.  Поэтому все сделано через static директорию

2020-10-28 18:48 UTC, technogleb requested changes
В целом все тоже хорошо, пара правок.

2020-10-28 18:48 UTC, technogleb commented on business_logic.py
> +    text = "\n изображений с асфальтом: " + str(results[0])
Много раз складывать строки - не очень хорошая практика. Лучше сделать форматированием. Если строка, это большой текст, можно класть его в тройные кавычки

2020-10-28 18:48 UTC, technogleb commented on main.py
> +app = Flask(__name__, static_url_path='/static')
Абсолютный путь идет от корня проекта?

2020-10-28 18:48 UTC, technogleb commented on business_logic.py
> +    return "всего машин 1"
Это просто заглушка пока?

2020-10-28 18:48 UTC, technogleb commented on webapp/config.py
> +SECRET_KEY = "gfdsSDRGDFBw345678kljhkjgh"
Лучше SECRET_KEY делать как os.getenv('SECRET_KEY', '')

2020-10-29 12:43 UTC, pavelbystrov1 commented on main.py
> +app = Flask(__name__, static_url_path='/static')
Да,  я взял этот код из примера по flask

2020-10-29 12:45 UTC, pavelbystrov1 commented on business_logic.py
> +    return "всего машин 1"
Да, Марина если успеет разобраться - я вставлю сюда посчитанные данные

2020-10-29 12:46 UTC, pavelbystrov1 commented on webapp/config.py
> +SECRET_KEY = "gfdsSDRGDFBw345678kljhkjgh"
И задавать при старте?

2020-10-29 14:30 UTC, pavelbystrov1 commented on business_logic.py
> +    text = "\n изображений с асфальтом: " + str(results[0])
Исправил

2020-10-29 14:30 UTC, pavelbystrov1 commented on webapp/config.py
> +SECRET_KEY = "gfdsSDRGDFBw345678kljhkjgh"
Исправил

2020-10-31 08:33 UTC, technogleb approved these changes
👌 мерджу

2020-10-31 08:34 UTC, merged