Bot keyboard
pandademonium/Object-Detection-Telegram-Bot pull request #4
Opened 2020-10-01 19:07 UTC by pandademonium

2020-10-01 19:08 UTC, pandademonium commented
keyboard appears and works, bot reacts to pictures being sent to him, doesn't save or process them, can't make it send pictures

2020-10-02 11:45 UTC, pavelbystrov1 reviewed
vse OK, tol'ko botenv zrya v proekt dobavlen.

2020-10-03 08:37 UTC, technogleb requested changes
Ты случайно запушила bot_env - его не должно быть в окружении. 
Тебе необходимо удалить его вот таким образом https://stackoverflow.com/questions/6535362/gitignore-after-commit и запушить заново

2020-10-03 08:37 UTC, technogleb commented on bot.py
> +PROXY = {'proxy_url': PROXY_URL,
лучше на следующую строку перенеси, а так по этому файлу нет вопросов

2020-10-03 08:37 UTC, technogleb commented on handlers.py
> +    pass
А зачем pass в конце? Просто убрать забыла?

2020-10-03 08:37 UTC, technogleb commented on requirements.txt
> +emoji
reqs удали, у Паши уже были в его пулл-реквесте.

2020-10-03 08:57 UTC, pandademonium commented on requirements.txt
> +emoji
ок

2020-10-03 08:58 UTC, pandademonium commented on handlers.py
> +    pass
да

2020-10-03 08:58 UTC, pandademonium commented on bot.py
> +PROXY = {'proxy_url': PROXY_URL,
ок

2020-10-03 09:16 UTC, technogleb commented
Еще одно дополнение - мы теперь немного изменили структуру проекта, все исходники теперь должны быть внутри папки object_detection. Так принято в питоне делать.
Смерджи мастер в свою ветку, засунь свои .py файлы по боту внутрь детекшн и пришли изменения.

2020-10-03 18:56 UTC, technogleb commented
Все отлично, но положи модуль bot внутрь object_detection. Тут идея в том, что все исходники должны лежать внутри одной папки. А так все оч красиво

2020-10-03 19:18 UTC, merged

2020-10-04 14:44 UTC, technogleb reviewed
Все отлично!